# Generated by Django 6.0.2 on 2026-02-28 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bill",
            options={"ordering": ["-billing_year", "-billing_month", "-created_at"]},
        ),
        migrations.AddField(
            model_name="bill",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="payment_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bill",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="account_number",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="bill",
            name="utility_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("electricity", "Electricity"),
                    ("water", "Water"),
                    ("mobile", "Mobile"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="UtilityAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("electricity", "Electricity"),
                            ("water", "Water"),
                            ("mobile", "Mobile"),
                        ],
                        max_length=20,
                    ),
                ),
                ("account_number", models.CharField(max_length=100)),
                (
                    "account_name",
                    models.CharField(
                        help_text="e.g., 'Head Office', 'Branch 1', 'Factory'",
                        max_length=200,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        help_text="For mobile: Dialog, Mobitel, etc.",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["utility_type", "account_name"],
                "unique_together": {("user", "utility_type", "account_number")},
            },
        ),
        migrations.CreateModel(
            name="BudgetForecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "forecast_type",
                    models.CharField(
                        choices=[("6_months", "6 Months"), ("1_year", "1 Year")],
                        max_length=20,
                    ),
                ),
                ("start_month", models.IntegerField()),
                ("start_year", models.IntegerField()),
                (
                    "month_1_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "month_2_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "month_3_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "month_4_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "month_5_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "month_6_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "month_7_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_8_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_9_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_10_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_11_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "month_12_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "total_forecast",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bills.utilityaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="bill",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bills",
                to="bills.utilityaccount",
            ),
        ),
    ]
