# Generated by Django 6.0.2 on 2026-03-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0002_alter_bill_options_bill_notes_bill_payment_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilityaccount",
            name="account_name",
            field=models.CharField(
                help_text="e.g., Head Office, Restaurant, Pool", max_length=200
            ),
        ),
        migrations.DeleteModel(
            name="BudgetForecast",
        ),
    ]
