# Generated by Django 6.0.2 on 2026-03-06 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bills", "0003_alter_utilityaccount_account_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="notification_email",
            field=models.EmailField(
                blank=True,
                help_text="Optional: Email for payment reminder",
                max_length=255,
                null=True,
            ),
        ),
    ]
